#!/usr/bin/python3

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 3:
        print("usages: " + sys.argv[0] + " tag name")
        exit(-1)

    import os
    import subprocess
    TAGS = ["boj", "alg", "prg"]
    path = os.path.abspath(".")
    tag = sys.argv[1].lower()
    name = sys.argv[2]

    if tag not in TAGS:
        print("please, select in " + str(TAGS))
        exit(-1)

    folder = os.path.join(path, tag, name)
    if os.path.exists(folder):
        print("exists %s in %s" %(name, tag))
    else:
        os.mkdir(folder)
        os.chdir(folder)
        with open(name+".c", "w"):
            pass
        subprocess.Popen(["code", name+".c"])